import { BaseStorageManager } from "./BaseStorageManager";

/**
 * Explanation step structure
 */
export interface ExplanationStep {
    title: string;
    content: string;
}

/**
 * Explanation chat message
 */
export interface ExplanationChatMessage {
    role: "user" | "assistant";
    content: string;
    id: string;
}

/**
 * Complete explanation structure with context
 */
export interface Explanation {
    steps: ExplanationStep[];
    exerciseName: string;
    exerciseStatement: string;
    exerciseContext?: string;
    chatHistory?: ExplanationChatMessage[]; // Follow-up chat history
}

/**
 * Explanation data structure for a page
 * Maps exercise name to its explanation
 */
export interface ExplanationData {
    pageId: string;
    explanations: Record<string, Explanation>; // { "Ejercicio 1": { steps: [...], ... }, ... }
}

/**
 * Storage manager for exercise explanations
 * Saves and retrieves explanations generated by SqlTutorAgent
 */
export class ExplanationStorageManager extends BaseStorageManager {
    private static readonly STORAGE_KEY_PREFIX = 'explanation_data_';

    /**
     * Saves the explanation for a specific exercise
     * @param pageId Page ID
     * @param exerciseName Exercise name
     * @param exerciseStatement Exercise statement
     * @param explanation Generated explanation (steps only)
     * @param exerciseContext Exercise context (optional)
     */
    static async saveExplanation(
        pageId: string,
        exerciseName: string,
        exerciseStatement: string,
        explanation: { steps: ExplanationStep[] },
        exerciseContext?: string
    ): Promise<void> {
        // Get existing explanations for this page
        const existingData = await this.getExplanationData(pageId);

        const fullExplanation: Explanation = {
            steps: explanation.steps,
            exerciseName,
            exerciseStatement,
            exerciseContext
        };

        const data: ExplanationData = {
            pageId,
            explanations: existingData?.explanations
                ? { ...existingData.explanations, [exerciseName]: fullExplanation }
                : { [exerciseName]: fullExplanation }
        };

        await this.saveData(this.STORAGE_KEY_PREFIX, pageId, data);
    }

    /**
     * Retrieves all explanations for a page
     * @param pageId Page ID
     * @returns Explanation data or null if not exists
     */
    static async getExplanationData(pageId: string): Promise<(ExplanationData & { timestamp: number }) | null> {
        return await this.getData<ExplanationData>(this.STORAGE_KEY_PREFIX, pageId);
    }

    /**
     * Retrieves the explanation for a specific exercise
     * @param pageId Page ID
     * @param exerciseName Exercise name
     * @returns Explanation or null if not exists
     */
    static async getExplanation(pageId: string, exerciseName: string): Promise<Explanation | null> {
        const data = await this.getExplanationData(pageId);
        if (!data || !data.explanations[exerciseName]) {
            return null;
        }
        return data.explanations[exerciseName];
    }

    /**
     * Actualiza el historial de chat de una explicación
     * @param pageId ID de la página
     * @param exerciseName Nombre del ejercicio
     * @param chatHistory Historial de mensajes del chat
     */
    static async updateChatHistory(
        pageId: string,
        exerciseName: string,
        chatHistory: ExplanationChatMessage[]
    ): Promise<void> {
        const data = await this.getExplanationData(pageId);
        if (!data || !data.explanations[exerciseName]) {
            console.error(`No se encontró la explicación para actualizar el chat: ${exerciseName}`);
            return;
        }

        // Actualizar el historial de chat
        data.explanations[exerciseName].chatHistory = chatHistory;

        await this.saveData(this.STORAGE_KEY_PREFIX, pageId, {
            pageId: data.pageId,
            explanations: data.explanations
        });
    }

    /**
     * Elimina la explicación de un ejercicio específico
     * @param pageId ID de la página
     * @param exerciseName Nombre del ejercicio
     */
    static async removeExplanation(pageId: string, exerciseName: string): Promise<void> {
        const data = await this.getExplanationData(pageId);
        if (!data) return;

        delete data.explanations[exerciseName];

        // Si no quedan explicaciones, eliminar toda la entrada
        if (Object.keys(data.explanations).length === 0) {
            await this.removeExplanationData(pageId);
        } else {
            await this.saveData(this.STORAGE_KEY_PREFIX, pageId, {
                pageId: data.pageId,
                explanations: data.explanations
            });
        }
    }

    /**
     * Elimina todas las explicaciones de una página del storage
     * @param pageId ID de la página
     */
    static async removeExplanationData(pageId: string): Promise<void> {
        await this.removeData(this.STORAGE_KEY_PREFIX, pageId);
    }

    /**
     * Limpia todas las explicaciones almacenadas
     */
    static async clearAllExplanationData(): Promise<void> {
        await this.clearAllData(this.STORAGE_KEY_PREFIX);
    }

    /**
     * Verifica si existe una explicación para un ejercicio específico
     * @param pageId ID de la página
     * @param exerciseName Nombre del ejercicio
     * @returns true si existe la explicación, false en caso contrario
     */
    static async hasExplanation(pageId: string, exerciseName: string): Promise<boolean> {
        const explanation = await this.getExplanation(pageId, exerciseName);
        return explanation !== null;
    }

    /**
     * Verifica si existen datos guardados para una página
     * @param pageId ID de la página
     * @returns true si existen datos, false en caso contrario
     */
    static async hasExplanationData(pageId: string): Promise<boolean> {
        return await this.hasData(this.STORAGE_KEY_PREFIX, pageId);
    }

    /**
     * Obtiene la cantidad de días desde que se guardaron las explicaciones
     * @param pageId ID de la página
     * @returns Días transcurridos o null si no hay datos
     */
    static async getExplanationDataAge(pageId: string): Promise<number | null> {
        return await this.getDaysSinceLastUpdate(this.STORAGE_KEY_PREFIX, pageId);
    }

    /**
     * Obtiene la lista de nombres de ejercicios con explicaciones guardadas
     * @param pageId ID de la página
     * @returns Lista de nombres de ejercicios o array vacío si no hay datos
     */
    static async getExerciseNamesWithExplanations(pageId: string): Promise<string[]> {
        const data = await this.getExplanationData(pageId);
        if (!data) return [];
        return Object.keys(data.explanations);
    }
}
